name: "Bundle minimal nixvim on x86-64 Linux"
on:
  # push:
  # pull_request:
  workflow_dispatch:
jobs:
  bundle:
    name: Build minimal nixvim, bundle a AppImage and upload it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix bundle --bundler github:ralismark/nix-appimage ".#minimal"
      - run: cp "$(readlink nvim.AppImage)" /tmp/nixvim.AppImage
      - uses: actions/upload-artifact@v4
        with:
          name: nixvim-minimal.AppImage
          path: /tmp/nixvim.AppImage
